### PR TITLE
interesting test with chatgpt :

### PR DESCRIPTION
**Pull request by agaldemas-eridanis**
from HL7/FHIR schema to NGSI-LD yaml model example for Patient resource

with a few questions to the brave chatGPT I managed to get an NGSI-LD yaml model file of the Patient resource type from HL7/FHIR json schema page...

It could be interesting to dig a bit the possibilities, 
but at least it can be a simple way to produce entity model on demand...

what do you think @albertoabellagarcia ?

### CODE REVIEW

**Comment by agaldemas-eridanis** [comment]
for @JTrullier to be involved !!!

**Comment by agaldemas-eridanis** [comment]
to explain the process here are the 4 questions to chatGPT to produce NGSI-LD yaml Patient schema from HL7/FHIR schema page :
1. produce ngsi-ld yaml smart data model definition from FHIR https://hl7.org/fhir/patient.schema.json.html
   - answer a transformation yaml file, ok let's help him a bit to respect the standard:
2. interesting, but ngsi-ld need also a "type" property, with value "Patient" (the hl7 resource type)
   - ok it add type & id, but stiil a transformation, not a schema, then: 
3. OK, but I want the schema model in yaml, not a way to transcript !
   - OK, nice, the yaml is there, missing a few rules, no problem, another question:
5. but still not exactly the right result, to respect NGSI-LD standard the "resourceType" property should become the NGSI-LD "type" mandatory property

### => and then OK, it gives a nice yaml schema file  of HL7/FHIR Patient model 
in file [chatgpt-fhir-ngsi-ld-patient.yaml](https://github.com/eridanisfr/incubated/blob/master/SMART%20HEALTH/HL7/chatgpt-fhir-ngsi-ld-patient.yaml)

### the full conversation is presented in the other file [chatgpt-fhir2ngsi-ld.yaml](https://github.com/eridanisfr/incubated/blob/master/SMART%20HEALTH/HL7/chatgpt-fhir2ngsi-ld.yaml)

**Comment by agaldemas-eridanis** [comment]
after, in the same conversation I asked ChatGPT to produce the yaml schemas of the referenced **definitions** of the Patient HL7/FHIR schema, and "le tour était joué"

We can imagine a simple set of queries, where you just have to set the schema page url...
and after why not using using it in a loop, 
or even asking "him/her/it?" to infer on the global HL7/FHIR schema...(most probably not possible due to limitations with a free account...)

this process can be used with pages on schema.org like [Patient](https://schema.org/Patient)

**Comment by albertoabellagarcia** [comment]
I agree that chatGPT is quite wonderful but also not much reliable. I challenge you to check all the details because my experience is that there are tiny 'errors' in most of the technical answers (especially in programs) but I have not checked with data models.

**Pull request closed without merging**
