### PR TITLE
Proposed data models required for FEATS project.

### PR DESCRIPTION
**Pull request by davidteixeira**
These are the data models required for the FEATS project, within the scope of DIH2. We noticed that the validator [tool](https://github.com/smart-data-models/tools/tree/master/validator) looks for `schema.json` inside the `examples` folder for each model, thus that is where we placed the file.

### CODE REVIEW

**Review by albertoabellagarcia — CHANGES_REQUESTED** [review]
### General
1) README.md files are not necessary as long as they are created automatically once approved the data model
### Material
spec.md 
1) content does not meet the template. https://github.com/smart-data-models/data-models/blob/master/templates/dataModel/doc/spec-example.md
example.json
1) It would be good that id and type would be the first two properties
example.jsonld
1) It would be good that id and type would be the first two properties
schema.json
1) It should be located in the root of the directory not in examples directory
2) refWarehouse is pointing to the same model. What's the goal of it?
3) consider why all required properties have to be mandatory. the fewer the better.

### Robot
spec.md
 1) content does not meet the template. https://github.com/smart-data-models/data-models/blob/master/templates/dataModel/doc/spec-example.md
example-normalized-ld.jsonld 
1) dateCreated and dateModified are internal properties. No need to include them here.
schema.json
2) reference in properties refDestination, refPayload, refWorkorder will lead to a schema without definitions section. What is the goal? In case of need of general properties for several data models it is required to create a 'subject'-schema.json in the root of the subject for compiling these definitions

### Warehouse
spec.md 
1) content does not meet the template. https://github.com/smart-data-models/data-models/blob/master/templates/dataModel/doc/spec-example.md
example-normalized.json 
1) dateCreated and dateModified are internal properties. No need to include them here.
example.json
1) It would be good that id and type would be the first two properties
example.jsonld
1) It would be good that id and type would be the first two properties
example-normalized-ld.jsonld 
1) it should be named example-normalized.jsonld 
schema.json
1) it should be on the root of warehouse directory
2) consider why all required properties have to be mandatory. the fewer the better.
 
### workorder 
apply previous recommendations

### workorder item
apply previous recommendations

### workStation item
apply previous recommendations

**Comment by davidteixeira** [comment]
@albertoabellagarcia regarding the `refWarehouse` attribute in Material and the `refDestination`, `refPayload` and `refWorkorder` attributes in Robot, our goal is to make a reference to the ID of another entity. For instance, a Robot shall have a `refDestination` which consists of the ID of a work station. It will then query the context broker using this ID to get the location of the work station. How should we build our data models to reflect these goals?

**Comment by albertoabellagarcia** [comment]
A work station is a place where the robot has to do something inside a warehouse. It should be an array of relationships in the warehouse model pointing to the workstations that are available. Regarding workstations location is necessary but possible also another property name placement, which defines in a 'room' where this element is situated. Resolution of coordinates but for big warehouses is not enough for practical uses. For placement see the definition on this json schema: https://github.com/smart-data-models/incubated/blob/master/multisensor/schema.json

**Comment by davidteixeira** [comment]
In the specific case of FEATS, `warehouse` refers to the automatic warehouse, an equipment which stores raw material (and not an actual warehouse). So it acts as another stopping point for the robot. How should we change our `$ref` to make a reference to other types of entities?

**Comment by davidteixeira** [comment]
We have pushed a new commit with the latest changes. Could you please review, @albertoabellagarcia ? Thank you.

**Pull request merged**
